const products=[
{id:1,n:'Orthopedic Pet Bed',c:'Beds & Comfort',p:49.99,img:'prod_bed.jpg',tag:'COMFORT',r:128},
{id:2,n:'Plush Elephant Toy',c:'Toys',p:14.99,img:'prod_elephant.jpg',tag:'PLAY',r:96},
{id:3,n:'Premium Leather Collar',c:'Walking & Outdoor',p:24.99,img:'prod_collar.jpg',tag:'WALK',r:84},
{id:4,n:'Stainless Steel Bowl',c:'Feeding',p:19.99,img:'prod_bowl.jpg',tag:'FEEDING',r:112},
{id:5,n:'Deshedding Brush',c:'Grooming',p:24.99,img:'prod_brush.jpg',tag:'GROOMING',r:76},
{id:6,n:'Pet Carrier',c:'Travel',p:59.99,img:'prod_carrier.jpg',tag:'TRAVEL',r:91},
{id:7,n:'Rope Chew Toy',c:'Toys',p:12.99,img:'prod_rope.jpg',tag:'PLAY',r:67},
{id:8,n:'No-Pull Harness',c:'Walking & Outdoor',p:34.99,img:'prod_harness.jpg',tag:'WALK',r:103}
];
let cart=JSON.parse(localStorage.getItem('pawCart')||'[]'), wish=JSON.parse(localStorage.getItem('pawWish')||'[]');
const $=s=>document.querySelector(s); const grid=$('#grid');
function save(){localStorage.setItem('pawCart',JSON.stringify(cart));localStorage.setItem('pawWish',JSON.stringify(wish));updateCounts()}
function updateCounts(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.q,0);$('#wishCount').textContent=wish.length}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function render(){let arr=[...products];const q=$('#search').value.toLowerCase(), c=$('#category').value, s=$('#sort').value; if(q)arr=arr.filter(x=>(x.n+x.c).toLowerCase().includes(q));if(c!=='all')arr=arr.filter(x=>x.c===c);if(s==='low')arr.sort((a,b)=>a.p-b.p);if(s==='high')arr.sort((a,b)=>b.p-a.p);if(s==='az')arr.sort((a,b)=>a.n.localeCompare(b.n));grid.innerHTML=arr.map(x=>`<article class="product"><button class="heart" data-w="${x.id}">${wish.includes(x.id)?'♥':'♡'}</button><div class="photo"><img src="assets/${x.img}" alt="${x.n}"></div><div class="pbody"><span class="tag">${x.tag}</span><h3>${x.n}</h3><div class="stars">★★★★★ <small>(${x.r})</small></div><div class="priceRow"><span class="price">$${x.p.toFixed(2)}</span><button class="add" data-add="${x.id}">Add to cart</button></div></div></article>`).join('');grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));grid.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>toggleWish(+b.dataset.w))}
function add(id){const p=products.find(x=>x.id===id),i=cart.find(x=>x.id===id);i?i.q++:cart.push({id,q:1});save();toast(`${p.n} added to cart`)}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];save();render()}
function renderCart(){const box=$('#cartItems');if(!cart.length){box.innerHTML='<p>Your cart is empty.</p>';$('#total').textContent='$0.00';return}let total=0;box.innerHTML=cart.map(x=>{const p=products.find(a=>a.id===x.id);total+=p.p*x.q;return `<div class="cartItem"><img src="assets/${p.img}" alt=""><div><b>${p.n}</b><div>$${p.p.toFixed(2)}</div><div class="qty"><button data-minus="${p.id}">−</button> ${x.q} <button data-plus="${p.id}">+</button></div></div><button data-remove="${p.id}">×</button></div>`}).join('');$('#total').textContent='$'+total.toFixed(2);box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart.find(x=>x.id==b.dataset.plus).q++;save();renderCart()});box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{let x=cart.find(x=>x.id==b.dataset.minus);x.q--;if(x.q<1)cart=cart.filter(a=>a.id!=b.dataset.minus);save();renderCart()});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!=b.dataset.remove);save();renderCart()})}
$('#search').oninput=render;$('#category').onchange=render;$('#sort').onchange=render;$('#cartBtn').onclick=()=>{$('#drawer').classList.add('open');renderCart()};$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('open');$('#checkout').onclick=()=>toast('Demo checkout — connect your payment provider here.');$('#wishBtn').onclick=()=>toast(`${wish.length} saved favorite${wish.length===1?'':'s'}`);document.querySelectorAll('.cat').forEach(a=>a.onclick=()=>{$('#category').value=a.dataset.cat;render()});$('#supportForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Message sent — thank you!')};$('#newsletter').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Welcome to the PAW & HAVEN community!')};
updateCounts();render();
