const products=[
{id:1,name:'Cloudrest Orthopedic Bed',cat:'Beds',price:89.99,img:'orthopedic-bed.jpg',badge:'Best Seller',desc:'Supportive memory-foam comfort with a soft raised edge for restful naps.'},
{id:2,name:'Cozy Nest Bed',cat:'Beds',price:69.99,img:'bed.jpg',badge:'Popular',desc:'A plush everyday bed with a deep center for curling up.'},
{id:3,name:'Blue Enrichment Chew',cat:'Toys',price:18.99,img:'classic-toy.jpg',badge:'New',desc:'Durable enrichment toy designed to keep curious pets engaged.'},
{id:4,name:'Rope Play Tug',cat:'Toys',price:14.99,img:'toy.jpg',badge:'Popular',desc:'Textured rope toy for interactive play and satisfying chewing.'},
{id:5,name:'Everyday Comfort Harness',cat:'Walking',price:42.00,img:'dog-harness.jpg',badge:'Featured',desc:'Secure, padded support for comfortable daily walks.'},
{id:6,name:'Classic Leather Collar',cat:'Walking',price:24.99,img:'collar.jpg',badge:'Classic',desc:'Clean leather styling with a sturdy everyday buckle.'},
{id:7,name:'Studio Ceramic Bowl',cat:'Feeding',price:28.00,img:'bowl.jpg',badge:'Featured',desc:'Simple elevated styling for everyday meals and water.'},
{id:8,name:'Stainless Bowl Pair',cat:'Feeding',price:32.00,img:'steel-bowls.jpg',badge:'Best Seller',desc:'Two easy-clean stainless bowls for food and water.'},
{id:9,name:'Soft Bristle Grooming Set',cat:'Grooming',price:26.99,img:'grooming.jpg',badge:'New',desc:'Everyday brushes for gentle grooming and coat maintenance.'},
{id:10,name:'Self-Cleaning Brush',cat:'Grooming',price:22.99,img:'self-cleaning-brush.jpg',badge:'Popular',desc:'Comfortable pin brush with an easy-clean design.'},
{id:11,name:'City Pet Carrier',cat:'Travel',price:79.00,img:'carrier.jpg',badge:'Featured',desc:'Structured travel carrier with padded panels and easy access.'},
{id:12,name:'Weekend Travel Carrier',cat:'Travel',price:94.00,img:'travel-carrier.jpg',badge:'New',desc:'A roomy, polished carrier for weekend trips and vet visits.'},
{id:13,name:'Green Outdoor Tag',cat:'Outdoor',price:12.00,img:'outdoor.jpg',badge:'New',desc:'Lightweight outdoor accessory made for active adventures.'},
{id:14,name:'Custom Paw ID Tag',cat:'Outdoor',price:19.99,img:'custom-id-tag.jpg',badge:'Personalized',desc:'A simple engraved-style tag for everyday identification.'},
{id:15,name:'Quilted Winter Jacket',cat:'Apparel',price:54.99,img:'winter-jacket.jpg',badge:'Seasonal',desc:'Warm quilted layer for chilly walks and outdoor mornings.'},
{id:16,name:'Soft Everyday Pet Jacket',cat:'Apparel',price:48.99,img:'apparel.jpg',badge:'New',desc:'Lightweight comfort layer with an easy everyday fit.'}
];
let filter='All',query='',sort='featured';
let cart=[],wish=[];
try{cart=JSON.parse(localStorage.getItem('pawCart')||'[]');wish=JSON.parse(localStorage.getItem('pawWish')||'[]')}catch(e){cart=[];wish=[]}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(v){return '$'+v.toFixed(2)}
function save(){try{localStorage.setItem('pawCart',JSON.stringify(cart));localStorage.setItem('pawWish',JSON.stringify(wish))}catch(e){}updateCounts()}
function updateCounts(){$('#cartCount').textContent=cart.reduce((a,i)=>a+i.qty,0);$('#wishCount').textContent=wish.length}
function filtered(){let list=products.filter(p=>(filter==='All'||p.cat===filter)&&(`${p.name} ${p.cat} ${p.desc}`.toLowerCase().includes(query.toLowerCase())));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='az')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function renderProducts(){const box=$('#products');const list=filtered();box.innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-media"><img src="assets/images/${p.img}" alt="${p.name}"><span class="badge">${p.badge}</span><button class="wish ${wish.includes(p.id)?'active':''}" data-wish="${p.id}" aria-label="Save ${p.name}">${wish.includes(p.id)?'♥':'♡'}</button></div><div class="product-body"><span class="product-category">${p.cat.toUpperCase()}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="product-foot"><strong class="price">${money(p.price)}</strong><button class="add-btn" data-add="${p.id}">Add to cart</button></div></div></article>`).join(''):`<div class="empty" style="grid-column:1/-1;padding:50px;text-align:center;color:#75665d">No products matched your search.</div>`;box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));box.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(+b.dataset.wish));box.querySelectorAll('.product-media img').forEach((im,i)=>im.onclick=()=>openProduct(list[i].id))}
function add(id){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();renderCart();toast(`${p.name} added to cart`)}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];save();renderProducts();if($('#wishPanel').classList.contains('open'))renderWish();toast(wish.includes(id)?'Saved to wishlist':'Removed from wishlist')}
function renderCart(){const box=$('#cartItems');if(!cart.length){box.innerHTML='<div style="padding:50px 0;text-align:center;color:#75665d;font-size:12px">Your cart is empty.<br><br><a href="#shop" style="color:#8c5137;font-weight:800" id="emptyShop">Start shopping →</a></div>';$('#cartTotal').textContent='$0.00';return}box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-row"><img src="assets/images/${p.img}" alt="${p.name}"><div><b>${p.name}</b><small>${money(p.price)}</small><div class="qty"><button data-dec="${p.id}">−</button><span>${i.qty}</span><button data-inc="${p.id}">+</button><button class="remove" data-rem="${p.id}">Remove</button></div></div><strong>${money(p.price*i.qty)}</strong></div>`}).join('');box.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.inc,1));box.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.dec,-1));box.querySelectorAll('[data-rem]').forEach(b=>b.onclick=()=>removeItem(+b.dataset.rem));$('#cartTotal').textContent=money(cart.reduce((a,i)=>a+products.find(p=>p.id===i.id).price*i.qty,0))}
function changeQty(id,n){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=n;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart()}
function removeItem(id){cart=cart.filter(x=>x.id!==id);save();renderCart()}
function openCart(){$('#cartDrawer').classList.add('open');$('#drawerOverlay').classList.add('open');renderCart()}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerOverlay').classList.remove('open')}
function openProduct(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-product"><img src="assets/images/${p.img}" alt="${p.name}"><div><span class="eyebrow">${p.cat.toUpperCase()}</span><h2>${p.name}</h2><p>${p.desc} Designed as a practical, comfortable addition to your pet's daily routine.</p><div class="modal-price">${money(p.price)}</div><button class="btn primary" data-modal-add="${p.id}">Add to cart →</button></div></div>`;$('#productModal').classList.add('open');$('#productModal [data-modal-add]').onclick=()=>{add(id);$('#productModal').classList.remove('open')}}
function openWish(){renderWish();$('#wishPanel').classList.add('open')}
function renderWish(){const box=$('#wishItems');if(!wish.length){box.innerHTML='<p style="color:#75665d;font-size:12px">No saved favorites yet. Tap the heart on a product to save it.</p>';return}box.innerHTML='<div class="wish-list">'+wish.map(id=>{const p=products.find(x=>x.id===id);return `<div class="wish-item"><img src="assets/images/${p.img}" alt="${p.name}"><div><b>${p.name}</b><span>${money(p.price)}</span><button class="add-btn" data-wish-add="${p.id}">Add to cart</button></div></div>`}).join('')+'</div>';box.querySelectorAll('[data-wish-add]').forEach(b=>b.onclick=()=>add(+b.dataset.wishAdd))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function setFilter(v){filter=v;$$('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===v));renderProducts();$('#shop').scrollIntoView({behavior:'smooth',block:'start'})}
$$('[data-filter]').forEach(el=>el.addEventListener('click',e=>{const v=el.dataset.filter;if(v)setFilter(v)}));
$('#searchInput').addEventListener('input',e=>{query=e.target.value;renderProducts()});$('#sortSelect').addEventListener('change',e=>{sort=e.target.value;renderProducts()});
$('#searchOpen').onclick=()=>{$('#searchPanel').classList.add('open');setTimeout(()=>$('#searchPanelInput').focus(),50)};$('#searchClose').onclick=()=>$('#searchPanel').classList.remove('open');$('#searchPanelInput').addEventListener('input',e=>{query=e.target.value;renderProducts();if(e.target.value)$('#shop').scrollIntoView({behavior:'smooth'})});
$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeCart;$('#drawerOverlay').onclick=closeCart;$('#wishOpen').onclick=openWish;
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));document.addEventListener('click',e=>{if(e.target.classList.contains('modal'))e.target.classList.remove('open')});
$('#checkoutBtn').onclick=()=>toast(cart.length?'Checkout is ready for a payment integration.':'Your cart is empty');
$('#supportForm').onsubmit=e=>{e.preventDefault();$('#supportStatus').textContent='Thanks! Your message is ready to be connected to a real support inbox.';e.target.reset();toast('Support message prepared')};$('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('You’re on the list — thank you!')};
$('#menuOpen').onclick=()=>$('#mobileMenu').classList.add('open');$('#menuClose').onclick=()=>$('#mobileMenu').classList.remove('open');$$('#mobileMenu a').forEach(a=>a.onclick=()=>$('#mobileMenu').classList.remove('open'));
updateCounts();renderProducts();renderCart();
